### ISSUE TITLE
ChatOpenAI LLMChain handleLLMNewToken constructor chain doesnt trigger

### ISSUE THREAD

**Issue by jacobrosenthal** [langchain-ai/langchainjs#1079]
```
  const model = new ChatOpenAI({
    temperature: 0,
    streaming: true,
  });

  const llmChain = new LLMChain({
    llm: model,
    prompt: ChatPromptTemplate.fromPromptMessages([
      SystemMessagePromptTemplate.fromTemplate("tell me a joke about:"),
      HumanMessagePromptTemplate.fromTemplate("{input}"),
    ]),

    callbacks: [
      BaseCallbackHandler.fromMethods({
        handleLLMNewToken: async (token: string) => {
          console.log(token);
        },
      }),
    ],
  });

  const result = await llmChain.call({ input: "dogs" },);
```

This doesnt output anything. The documents led me to believe you could put it on the chain constructor. It does work on both the Model constructor and on the `.call`

**Comment by jacobrosenthal** [comment]
I think the model is wiping out the chain handlers

doesnt work, callbacks on chain constructor
```
basechain call configure
CallbackManager {
  handlers: [
    CustomHandler {
      ignoreLLM: false,
      ignoreChain: false,
      ignoreAgent: false,
      name: 'custom_handler'
    }
  ],
  inheritableHandlers: [],
  name: 'callback_manager',
  _parentRunId: undefined
}
chatmodel generate configure
CallbackManager {
  handlers: [],
  inheritableHandlers: [],
  name: 'callback_manager',
  _parentRunId: '23435965-06b1-438e-975f-b304af5c379b'
}
```



does work, callbacks on model constructor
```
basechain call configure
undefined
chatmodel generate configure
CallbackManager {
  handlers: [
    CustomHandler {
      ignoreLLM: false,
      ignoreChain: false,
      ignoreAgent: false,
      name: 'custom_handler'
    }
  ],
  inheritableHandlers: [],
  name: 'callback_manager',
  _parentRunId: undefined
}
```

**Comment by agola11** [comment]
Sorry if this is confusing. Request callbacks (those passed to `call`, `run` etc) are passed through to child objects (i.e. LLMChain -> Model). However, constructor callbacks are scoped to the object you place them on. In this case, you attach the callbacks to `LLMChain`, so they won't get inherited by the model is uses, and it's the model that fires off the `handleLLMNewToken` event, hence you get no output.

Passing through works though because those callbacks get passed all the way through.

anything we can do to make this more clear?

**Comment by agola11** [comment]
https://js.langchain.com/docs/production/callbacks/#multiple-handlers

**Comment by jacobrosenthal** [comment]
Not sure I understand. Are we saying this is the intended behavior. you can not get handleLLMNewToken on a chain constructor?

**Comment by agola11** [comment]
Rn, you'd have to attach it to the LLM constructor or pass it through in call

**Comment by thivy** [comment]
I have streaming enabled and the handleLLMNewToken callback function is getting executed but the handleLLMEnd never gets called.

**Comment by davidtom** [comment]
I've read through the explanations in this thread and the documentation, but I still don't understand how to set up callbacks to track cumulative token usage and request counts across an LLM Chain call. When using version `0.0.58` of langchainjs, the following set up worked as I needed:
```
export class MyCallbackManager extends CallbackManager {
  private totalTokens: number;
  private successfulRequests: number;

  constructor() {
    super();

    this.totalTokens = 0;
    this.successfulRequests = 0;
  }

  async handleLLMNewToken(token: string, verbose?: boolean | undefined) {
    this.totalTokens += 1;
  }

  async handleLLMEnd(outputs, verbose?: boolean | undefined) {
    if (outputs.llmOutput) {
      this.successfulRequests += 1;
    }

    console.log('Completed LLM call', {
      totalTokens: this.totalTokens,
      successfulRequests: this.successfulRequests,
    });
  }

  getLLMData(): {
    totalTokens: number;
    promptTokens: number;
    completionTokens: number;
    successfulRequests: number;
  } {
    return {
      totalTokens: this.totalTokens,
      successfulRequests: this.successfulRequests,
    };
  }
}

const callbackManager = new MyCallbackManager();

const model = new ChatOpenAI({
  openAIApiKey: process.env.OPENAI_API_KEY,
  callbackManager,
  streaming: true,
});

const llmChain = new LLMChain({
  llm: model,
  prompt: summaryChatPromptTemplate,
});


const run = async () => Promise<void> => {
  const result = await llmChain.call({ text: texts[0] })
  const { totalTokens, successfulRequests } = callbackManager.getLLMData();
}

run();
```

If the Model was called multiple times, the `totalTokens` would be the sum of the tokens received by each call of the model. Same for the the count of `successfulRequests`.

However, when using langchainjs version `0.0.68`, no matter where I pass an instance of `MyCallbackManager` - either in the model constructor, the LLM chain constructor, or the LLM Chain `call()` method - the instance of `MyCallbackManager` never has any of this data. From what I can tell by logging in the `MyCallbackManager` constructor, a completely new instance is created by whatever I pass the instance to via `callbacks`. As a result, I can never access data from any of these objects. All I can do is log the data out.

Am I misunderstanding how this all should be set up? Or is it not possible to do what I'm trying to do here?

I'm also confused because we have another project that uses the Python Langchain library, and the set up described above works just fine there. Is langchainjs deviating from that heavily from the Python version?

**Comment by agola11** [comment]
@davidtom -- sorry you're having issues. Let me know if your issue still persists on `main` -- just merged a PR that prevents copying handlers in `configure`. I think that was causing a lot of issues. If that doesn't fix, lmk and I'll prioritize investigating more.

**Comment by davidtom** [comment]
@agola11 Thanks for the quick response! I'll try running our project off `main` as soon as I can and follow up here!

**Comment by davidtom** [comment]
> @davidtom -- sorry you're having issues. Let me know if your issue still persists on `main` -- just merged a PR that prevents copying handlers in `configure`. I think that was causing a lot of issues. If that doesn't fix, lmk and I'll prioritize investigating more.

@agola11 Thank you for the quick response! I've tested the code changes on `main` and it looks like `MyCallbackManager` is now behaving as I need it to. So it seems like those changes are indeed the fix for the issue.

Any idea when a new version will be released with those changes?
