### ISSUE TITLE
ChatAgentOutputParser failing on $JSON_BLOB in action invocation json with Claude

### ISSUE THREAD

**Issue by clareliguori** [langchain-ai/langchainjs#1399]
I'm using Anthropic Claude and frequently hit the error `Error: Unable to parse JSON response from chat agent.` when the chat agent tries to invoke a tool.  Claude appears to be very likely to interpret the action invocation instructions as needing to include the literal string `$JSON_BLOB` in the markdown, which breaks the JSON parsing.  

Example from the chat agent:

    Action:
    ```
    $JSON_BLOB  
    {
      "action": "my_action_name", 
      "action_input": "the action input goes here"
    }
    ```

Would it make sense to trim the `$JSON_BLOB` string out before the JSON parsing?
https://github.com/hwchase17/langchainjs/blob/01673d8496d27f0e84bb4ef4c51bf67eb6187f68/langchain/src/agents/chat/outputParser.ts#L14-L18

Trace:
```
    at ChatAgentOutputParser.parse (langchain/dist/agents/chat/outputParser.cjs:26:19)
    at ChatAgent._plan (langchain/dist/agents/agent.cjs:205:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (langchain/dist/agents/executor.cjs:85:28)
    at async AgentExecutor.call (langchain/dist/chains/base.cjs:68:28)
```
Langchain JS version 0.0.68

**Comment by jacoblee93** [comment]
We'd expect most agents are only really going to work with OpenAI at the moment - it'll likely require some prompt changes.

I was looking at this a while back and funnily enough just closed this - it was modifying an agent for LLMs rather than chat models like Claude: https://github.com/hwchase17/langchainjs/pull/565

Would you be up for reviving something like it?
