### ISSUE TITLE
Webpages, with Puppeteer

### ISSUE THREAD

**Issue by kamalkech** [langchain-ai/langchainjs#1496]
"langchain": "^0.0.88",

import { PuppeteerWebBaseLoader } from `langchain/document_loaders/web/puppeteer`;

 Cannot find module 'langchain/document_loaders/web/puppeteer' or its corresponding typ
e declarations.

**Comment by siddarthvader** [comment]
this is weird because I am actually able to work with Puppeteer. 

Context: I was actually working with puppeteer, would love to now what went wrong for you.

<img width="754" alt="Screenshot 2023-06-01 at 5 59 49 PM" src="https://github.com/hwchase17/langchainjs/assets/7977737/223152de-182a-4945-a918-f98754c7dd9e">

**Comment by tushar5563** [comment]
Cannot find module 'langchain/document_loaders/web/puppeteer' or its corresponding type declarations.
import  {PuppeteerWebBaseLoader} from "langchain/document_loaders/web/puppeteer"
can anyone give exact solution
![Screenshot 2024-12-12 151631](https://github.com/user-attachments/assets/48de7648-c0fe-4d1c-96a5-b4674498b7a8)
