### ISSUE TITLE
Langchain and Azure ChatOpenAI is not working

### ISSUE THREAD

**Issue by transmoga** [langchain-ai/langchainjs#1685]
I have **fully working** code for a chat model with OpenAI , Langchain, and NextJS

```
const llm = new ChatOpenAI({
  openAIApiKey: OPENAI_API_KEY,
  temperature: 0.9,
  streaming: true,
  callbackManager: CallbackManager.fromHandlers({
    handleLLMNewToken: async (token) => {
      await writer.ready;
      await writer.write(encoder.encode(`${token}`));
    },
    handleLLMEnd: async () => {
      await writer.ready;
      await writer.close();
    },
    handleLLMError: async (e) => {
      await writer.ready;
      await writer.abort(e);
    },
  }),
});
```
  
 If I change it to instead access an Azure OpenAI model, a model that works with Python and Langchain. I get no response from the API.  

```
const llm = new ChatOpenAI({
  openAIApiKey: "",
  azureOpenAIApiVersion: "",
  azureOpenAIApiKey: "",
  azureOpenAIApiInstanceName: "",
  azureOpenAIApiDeploymentName: "",
  streaming: true,
  temperature: 0.9,
  streaming: true,
  callbackManager: CallbackManager.fromHandlers({
    handleLLMNewToken: async (token) => {
      await writer.ready;
      await writer.write(encoder.encode(`${token}`));
    },
    handleLLMEnd: async () => {
      await writer.ready;
      await writer.close();
    },
    handleLLMError: async (e) => {
      await writer.ready;
      await writer.abort(e);
    },
  }),
});
```

**Comment by transmoga** [comment]
I am getting an error at the console of:

[error (Azure) OpenAI API key not found](url)

I have absolutely set the key.

**Comment by crisdevnull1** [comment]
The same thing happens in a project I'm working on, and according to the tests I'm doing it's because the URL always points to the wrong endpoint, no matter what value is set in azureOpenAIApiVersion the URL will always be wrong and always return status 400 or 404 I haven't been able to find a way to set this URL to the correct one at the time the call() method is executed. Any ideas?

**Comment by shanurrahman** [comment]
> The same thing happens in a project I'm working on, and according to the tests I'm doing it's because the URL always points to the wrong endpoint, no matter what value is set in azureOpenAIApiVersion the URL will always be wrong and always return status 400 or 404 I haven't been able to find a way to set this URL to the correct one at the time the call() method is executed. Any ideas?

It's pointing to 
https://{my-openai-instance}.openai.azure.com/openai/deployments/{my-openai-deployment}/embeddings

I tried all 3 of them `OpenAIChat`, `PromptLayerOpenAI`, `OpenAI`, all three are pointing to embeddings and not chat completion!

**Comment by transmoga** [comment]
I managed to get further when setting the following in the environment instead.  

export AZURE_OPENAI_API_KEY=""
export AZURE_OPENAI_API_INSTANCE_NAME=""
export AZURE_OPENAI_API_DEPLOYMENT_NAME=""
export AZURE_OPENAI_API_VERSION="2023-03-15-preview"

But, this just leads me to issues with the Axios library:

https://github.com/hwchase17/langchainjs/issues/1688

**Comment by shanurrahman** [comment]
Instead of using   `azureOpenAIApiInstanceName`, have you tried using `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` and `AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME`. also make sure to have an embeddings deployment alongside completions

refer: https://github.com/hwchase17/langchainjs/issues/1750#issuecomment-1626863774
