### ISSUE TITLE
keepseperator not working RecursiveCharacterTextSplitter

### ISSUE THREAD

**Issue by samipshah100** [langchain-ai/langchainjs#1791]
**Issue**
I am using RecursiveCharacterTextSplitter and splitting text by separator

I am using keepSeparator to false, but the output chunks still include the sepertor. please see below, my seperator is: `---separator---`

**Langchain version**:
"langchain": "^0.0.98",

**Code** 
```
 const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 200,
      keepSeparator: false,
      separators: ['---separator---', '\n'],
    });
```

**Output**
```
Document {
    pageContent: `---separator---      "Title": "test",            "Content": "test content.",  ---separator---    < end of chunks >`,
    metadata: { loc: [Object] }
  }
```

**Issue**
Output is including the separator string : `---separator---`

**Expected outcome**
Output chunk should not include the separator string.

Can someone please advise. Thanks.

**Comment by devstein** [comment]
_Answer generated by a 🤖_

## Answer
The issue seems to be in the `mergeSplits` method of the `TextSplitter` class. This method is responsible for merging the split chunks of text back together. When `keepSeparator` is set to `false`, the separator should not be included in the merged text. However, in the current implementation, the separator is always included in the merged text, regardless of the value of `keepSeparator`.

Here is the problematic part of the code:

```ts
mergeSplits(splits: string[], separator: string): string[] {
    // ...
    const doc = this.joinDocs(currentDoc, separator);
    // ...
}
```

In the above code, `separator` is always passed to the `joinDocs` method, which means the separator is always included in the merged text.

To fix this issue, you should modify the `mergeSplits` method to only include the separator in the merged text when `keepSeparator` is `true`. Here is the corrected code:

```ts
mergeSplits(splits: string[], separator: string): string[] {
    // ...
    const doc = this.joinDocs(currentDoc, this.keepSeparator ? separator : "");
    // ...
}
```

In the corrected code, `separator` is only passed to the `joinDocs` method when `keepSeparator` is `true`. Otherwise, an empty string is passed, which means no separator is included in the merged text.

## Source
- [langchain/src/text_splitter.ts](https://github.com/hwchase17/langchainjs/blob/-/langchain/src/text_splitter.ts)

---

This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

**Comment by samipshah100** [comment]
Great now if only AI could automatically create the pull request, run the tests , merge the code and notify me. 

Anyone wanna spin off a langchain agent for this? 😂
