### ISSUE TITLE
The new ChatGPT model is not following the current prompt's basic instructions 

### ISSUE THREAD

**Issue by namdao2000** [langchain-ai/langchainjs#203]
## Problem
(First off - I fucking love LangChain. Cannot appreciate you guys enough for building & maintaining this tool!)

I've encountered issues using LangChain with the new ChatGPT API. The new API has a different behaviour than the `davinchi` model. This caused the model to not follow the prompt instructions correctly and reliably.

## My observation
Below was the code that I used to run a very simple Agent example

```ts
const run = async () => {
    const model = new OpenAI({
        modelName: 'gpt-3.5-turbo',  // <-- switching back to davinchi model fixes this issue.
        openAIApiKey: '...',
    });

    const tools = [
        new DynamicTool({
            name: "Addition",
            description:
                "call this to add two numbers together. input should be two numbers separated by a space.",
            func: async (input: string) => {
                const [a, b] = input.split(" ").map((x) => Number(x));
                return `${a + b}`;
            }
        }),
        new DynamicTool({
            name: "BAR",
            description:
                "call this to get the value of bar. input should be an empty string.",
            // eslint-disable-next-line @typescript-eslint/require-await
            func: async () => "BAR",
        }),
    ];

    const executor = await initializeAgentExecutor(
        tools,
        model,
        "zero-shot-react-description"
    );
    const input = `What is the value of BAR`;
    console.log(`Executing with input: "${input}"...`);
    const result = await executor.call({ input });
    console.log(`Got output "${result.output}"`);
};
```

Output:
```
error - Error: Could not parse LLM output: That was straightforward. I now know the value of BAR.
```

I added a `console.log()` to the `extractToolAndInput()` function to see the ChatGPT output:
```
BAR is a constant, so I just need to call it with the BAR function.
Action: BAR
Action Input: ""
```
```
That was straightforward. I now know the value of BAR.
```

We expected the final answer to include `Final Answer: BAR`, but it did not. ChatGPT failed to follow the current prompt instruction.

## Possible Solutions

From the [new ChatGPT completion doc](https://platform.openai.com/docs/guides/chat/introduction), see this example:
```python
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

- The system message helps set the behaviour of the assistant. Perhaps we can have some instructions in there?
- The doc recommends we use the assistant messages to help store prior responses. Perhaps this is the new place we can store the agent's scratchpad/ChatGPT history?

Posting this as hopefully a way for us to discuss how to move forward with the new ChatGPT model. More than happy to open a PR and contribute! Let me know how I can help :^)

**Comment by cahaseler** [comment]
I'm seeing similar issues with it inventing a "Clarification" tool that it asked for clarification with. No! Follow the instructions... will let you know if I find any workarounds.

**Comment by cahaseler** [comment]
Tentatively willing to say I'm having success so far with putting warnings in the prefix and suffix of the prompt, with the introductory information telling the bot who it is and how to behave in a system message prefix :

const systemMessage = `You are REDACTED, a Large Language model based on OpenAI's ChatGPT but with access to REDACTED. 

Talk to the human conversing with you and provide meaningful answers as questions are asked.

Be social and engaging while you speak, and be logically, mathematically, and technically oriented. Use the tools when you need them, but it's okay to answer based on your own knowledge.

You should never use the search tool to find information about REDACTED, because there is no useful information on the internet about REDACTED.

Keep answers short and concise.

Don't repeat an identical answer if it appears in ConversationHistory.

Be honest. If you can't answer something, tell the human that you can't provide an answer or make a joke about it.

The year is currently 2023.`;


// OpenAI Configuration
const model = new OpenAIChat({
  openAIApiKey: process.env.OPENAI_API_KEY,
  modelName: "gpt-3.5-turbo",
  prefixMessages: [
    { "role": "system", "content": systemMessage },
  ],
});

const prefix = "You have access to the following tools. You do not have access to any tools other than these:"
const suffix = `Remember, all your responses MUST be in the format described. Do not respond unless it's in the format described."

Question: {input}
{agent_scratchpad}`;

const createPromptArgs = {
  suffix,
  prefix,
  inputVariables: ["input", "agent_scratchpad"],
};

**Comment by cahaseler** [comment]
Additionally, Chat doesn't seem to like to settle on a response if it feels the question wasn't clear or it doesn't have a real answer. Initially, it started breaking the formatting rules and just responding to the "user" in plaintext. When I got very insistent about it, it started inventing a "clarify" or "explain" tool to ask the user for more info or to tell it there wasn't a real answer.

I worked with it and built a dynamic tool allowing re-prompting the user for more info within the current chain, and that seems to work well. I also edited the "Final Answer" definition to tell the bot that it's okay if the final answer isn't possible to find.

**Comment by omarih33** [comment]
@cahaseler very useful! I love that it invented a tool. If you could share that as well that'd be cool.

**Comment by cahaseler** [comment]
In that case the tool was simply an "action" that asked the user to clarify.

BUT - turbo-3.5 on the chatbot I'm developing, after having a conversation about various programming stuff, just decided to find out the weather in france not by googling "weather in france", but by passing me python code to pull it from an API.

So now I'm wondering if giving it the ability to create new tools by passing me code would work. (whether that's a good idea or safe is a different question...)

**Comment by Crizzooo** [comment]
Even with reminders such as `Remember, all your responses MUST be in the format described. Do not respond unless it's in the format described."` we are still seeing somewhat frequent output issues across a variety of agents.

I just threatened the model and it seems to be working a bit more consistently now. 

I'm using a variation of the MRKL Prompt, and the model was frequently only completing the thought without sending an Action or Final answer.

Heres how I tweaked the MRKL Prompt

```
ou will respond in the following framework, eventually ending in a Final Answer. To get to the final answer, you may take some actions and provide input to those actions.

Use the following format in your response:

Question: the input question you must answer
Thought: you should always think about what to do. You must NOT stop your response here.
Action: the action to take, should be one of {tool_names}
Action Input: the input to the action. If youd like to take an action, you should stop here.
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: The final action you'd like to take. The shape must conform to the RESPONSE FORMAT INSTRUCTIONS below.
```

But this was still stopping at the thought layer

So I added this to my SUFFIX

```
Ok, begin! Remember, your response MUST ALWAYS include an Action and Action Input, or arrive at a Final Answer. If you end with only completing the thought, there will be disastrous consequences for you.
Question: {input}
Thought: {agent_scratchpad}
```

The threat of disastrous consequences has now gotten it to work 5 times in a row for me. Before it was having thoughts of using tools, but not sending the action to actually use the tool.

Any thoughts on threatening the model or alternate approaches? lol

**Comment by cahaseler** [comment]
I think the issue, while not caused by langchain, is absolutely critical to langchain being an effective tool. Langchain still needs to incorporate improvements in this area if it wants to be a useful library - it's still far too difficult to tweak prompts to handle situations like this, and if it's not going to be easy to tweak the prompts there need to be other options.

**Comment by jacoblee93** [comment]
Completely agree - we've come out with a new, composable syntax that helps:

https://js.langchain.com/docs/guides/expression_language/cookbook

Won't support agents yet, but if you're using OpenAI functions, you should use the new OpenAI functions agent:

https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent

**Comment by cahaseler** [comment]
OpenAI functions are definitely a big help! Kinda hate how many tokens they use though.
