### ISSUE TITLE
Delete/upsert support in FAISS

### ISSUE THREAD

**Issue by jacoblee93** [langchain-ai/langchainjs#2427]
We've had a request for better delete/upsert support for the FAISS store - @ewfian would you be able to tackle adding it to the underlying package?

https://twitter.com/vsrisaijyothi/status/1696054437348069807?s=20

**Comment by ewfian** [comment]
Confirmed that there is a [delete](https://python.langchain.com/docs/integrations/vectorstores/faiss#delete) method in the Python implementation, in order to maintain consistency, will implementing [remove_ids](https://github.com/langchain-ai/langchain/blob/cf122b6269a841836a84940b5627c5444e069087/libs/langchain/langchain/vectorstores/faiss.py#L501) on faiss-node side to support the delete

**Comment by jacoblee93** [comment]
Much appreciated!

**Comment by vkkon** [comment]
How can I delete or update a document from the HNSWLib index in Javascript ? Much appreciated. Thanks
