### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'message') when chat with Google Palm

### ISSUE THREAD

**Issue by Nanyi-Jiang** [langchain-ai/langchainjs#2641]
Version of Langchain: 0.0.132

Hi there, I'm using `ChatGooglePaLM` with `call` method, but if I send the specific message, there will be an error which is `Cannot read properties of undefined (reading 'message')`

The messages I provide the model is something like:
`HumanMessage {
    lc_serializable: true,
    lc_kwargs: {
      content: 'C\n\n## Cr by [A](https://www.google.com) at Google',
      additional_kwargs: {}
    },
    lc_namespace: [ 'langchain', 'schema' ],
    content: 'C\n\n## Cr by [A](https://www.google.com) at Google',
    name: undefined,
    additional_kwargs: {}
  }`

**Comment by afirstenberg** [comment]
The underlying issues here are likely:

- There are no results that were returned. Which is likely because:
- Your API key was invalid

Double-check to make sure the API key you're either passing in or setting via the GOOGLE_PALM_API_KEY is one that you have gotten from the MakerSuite console and that it is valid. You may want to test it using the curl command suggested by the console as well.

It looks like the library isn't properly handling this error message, which is something that we should look at and address.

**Comment by afirstenberg** [comment]
Hrm. Upon further testing - I think I'm wrong. It does look like an error is getting thrown, or is supposed to be.

But that doesn't explain how you could be getting no results.

Can you provide an illustration of how you're calling it?

**Comment by Nanyi-Jiang** [comment]
Sure, here's how we define the model:
```
chatModel = new ChatGooglePaLM({
        apiKey: GOOGLE_PALM_API_KEY,
        ...baseChatOpts,
      })
```
with `baseChatOpts` like this:
```
{
  modelName: 'models/chat-bison-001',
  temperature: 0.2,
  streaming: true,
  maxTokens: undefined,
  callbacks: [ { handleLLMNewToken: [Function: handleLLMNewToken] } ]
}
```
And we use `.call` method by passing in BaseMessage[] that looks like this:
```
HumanMessage
 { 
    lc_serializable: true, 
    lc_kwargs: { 
            content: 'C\n\n## Cr by [A](https://www.google.com) at Google', 
            additional_kwargs: {} 
    }, 
    lc_namespace: [ 'langchain', 'schema' ], 
    content: 'C\n\n## Cr by [A](https://www.google.com) at Google', 
    name: undefined, 
    additional_kwargs: {} 
}
```
