### ISSUE TITLE
Missing `mapStoredMessagesToChatMessages` and `mapChatMessagesToStoredMessages`

### ISSUE THREAD

**Issue by Knordy** [langchain-ai/langchainjs#3428]
We are currently building a `ChatMessageHistory` that will be used with `Prisma`. This `PrismaChatMessageHistory` will be used in the `ConversationalRetrievalQAChain`. For getting and adding the messages the `'langchain/stores/message/utils'` `mapStoredMessagesToChatMessages` and `mapChatMessagesToStoredMessages` must be used to convert the messages to the appropriate format. However these functions cannot be used:

`TS2307: Cannot find module  langchain/stores/message/utils  or its corresponding type declarations.`

Is there a reason this module cannot be found?

**Comment by Knordy** [comment]
Module `'langchain/src/stores/message/utils'` can also not be found, `BaseMessage` and `StoredMessage` are imported by the module `langchain/schema`. Both functions are are very small, but I would like to use the langchain functions instead of creating/copying my own.

```
export function mapStoredMessagesToChatMessages(
  messages: StoredMessage[],
): BaseMessage[] {
  return messages.map(mapStoredMessageToChatMessage);
}
```
and
```
export function mapChatMessagesToStoredMessages(
  messages: BaseMessage[],
): StoredMessage[] {
  return messages.map((message) => message.toDict());
}
```

**Comment by gcyrFednav** [comment]
for future ppl stumbling upon this error for other projects ( because i think this one is really a bug and should be fixed )

but i had the same issue while implementing a custom message store; and what fixed for me was using these imports instead.

`import {

    mapChatMessagesToStoredMessages,
    mapStoredMessagesToChatMessages
} from "langchain/dist/stores/message/utils";
import {BaseMessage, StoredMessage} from "@langchain/core/messages";
`


instead we gotta add that sweet sweet /dist/ to the path and stuff seems to work has a workaround.
