### ISSUE TITLE
How to fetch all documents from Pinecone Store namespace 

### ISSUE THREAD

**Issue by mubashirjamali101** [langchain-ai/langchainjs#3963]
# What I want?
```ts

import { PineconeStore } from 'langchain/vectorstores/pinecone';

/* create vector-store instance */
const vectorStore = await PineconeStore.fromExistingIndex(
  new OpenAIEmbeddings(),
  {
    pineconeIndex: index,
    textKey: 'text',
    namespace,
  },
);

const retriever = vectorStore.asRetriever({
  callbacks: [
    {
      handleRetrieverEnd(documents) {
        resolveWithDocuments(documents);
      },
    },
  ],
});

// fetches the RELEVANT document from the vector store
const documents = await retriever.getRelevantDocuments("")
```

I want to fetch all the documents instead of relevant. How can I do that?

**Comment by mubashirjamali101** [comment]
> Not a Langchain issue. Pinecone does not support this functionality. You have to do a clever workaround

Thanks for the reply.

Do you have any suggestion for me on how can I get a workaround for it?

as I am just a newbie to Lanchain and Pinecone.

Again, thank you for helping me.

**Comment by ElectricCodeGuy** [comment]
Hey so sorry, did not see my inbox. I used the following script :)
`// Import necessary modules
import { NextResponse } from 'next/server';
import {
  Pinecone,
  Index,
  QueryOptions,
  QueryResponse,
  RecordMetadata
} from '@pinecone-database/pinecone';

// Set dynamic mode since Nextjs Cache everything and you do not want to cache 1k results from your DB xD
//Only needed if you have a Nextjs API Route. 
export const dynamic = 'force-dynamic';

// Initialize a Pinecone client and reference a specific index and namespace
const pinecone: Pinecone = new Pinecone();
const index: Index = pinecone.index('<index-name>').namespace('<namespace>');

/**
 * Generates a random vector of specified length.
 * @param {number} length - The length of the vector.
 * @return {number[]} - The generated vector.
 */
function generateRandomVector(length: number): number[] {
  return Array.from({ length }, () => Math.random());
}

/**
 * Fetches records from Pinecone and updates their metadata.
 */
async function fetchAndProcessRecords() {
  // Generate a random query vector
  const randomVector = generateRandomVector(1536);

  // Set query options
  const queryOptions: QueryOptions = {
    vector: randomVector,
    topK: 1000,
    filter: {
      $and: [
        // Define your filtering logic here
      ]
    },
    includeMetadata: true
  };

  // Query the index and process the response
  const response: QueryResponse<RecordMetadata> = await index.query(queryOptions);

  for (const record of response.matches) {
    // Update and process each record as needed
    const updatedMetadata = { ...record.metadata, <new-metadata-key>: <new-value> };
    const updateData = { id: record.id, metadata: updatedMetadata };
    await index.update(updateData);
    console.log(`Record ${record.id} updated.`);
  }
  console.log('Completed processing records.');
}

// Function to handle incoming requests
export async function GET() {
  if (process.env.NEXT_IS_BUILD) {
    return NextResponse.json({ message: 'Skipped during build' }, { status: 200 });
  }

  // Begin the process of updating records
  for (let i = 0; i < <number-of-iterations>; i++) {
    console.log(`Iteration ${i + 1} of fetchAndProcessRecords`);
    await fetchAndProcessRecords();
  }

  return NextResponse.json({ message: 'Completed updating records' }, { status: 200 });
}
`

We're basically chucking a bunch of random vectors into the database to see what we get back. We then run this process a bunch of times, say around 1000 iterations.

Now, the cool part is what we do with the data we get. We can update it, delete it, or pretty much anything else we need. But here's a heads-up: since we're using random vectors, if you don’t set some filters and you’ve got a ton of data (imagine like a million vectors), you could be at it forever. It’s like finding a needle in a haystack. So, a little bit of filtering can save us a lot of time and hassle.
