### ISSUE TITLE
Dependency Resolution Issue with @pinecone-database/pinecone in langchain@0.1.5

### ISSUE THREAD

**Issue by natapol2547** [langchain-ai/langchainjs#4131]
I am encountering a dependency resolution issue while trying to install the langchain@0.1.5 package. The error seems to be related to conflicting versions of the @pinecone-database/pinecone package.

Error Message
```
While resolving: langchain@0.1.5
Found: @pinecone-database/pinecone@2.0.1
node_modules/@pinecone-database/pinecone
  @pinecone-database/pinecone@"*" from the root project
  @pinecone-database/pinecone@"^2.0.0" from @langchain/pinecone@0.0.1
  node_modules/@langchain/pinecone
    @langchain/pinecone@"*" from the root project

Could not resolve dependency:
peerOptional @pinecone-database/pinecone@"^1.1.0" from langchain@0.1.5
node_modules/langchain
  langchain@"^0.1.5" from the root project

Conflicting peer dependency: @pinecone-database/pinecone@1.1.3
node_modules/@pinecone-database/pinecone
  peerOptional @pinecone-database/pinecone@"^1.1.0" from langchain@0.1.5
  node_modules/langchain
    langchain@"^0.1.5" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

Steps to Reproduce
1. npm create svelte@latest my-app
2. cd my-app
3. npm install
4. npm install -S langchain
5. npm install -S @langchain/pinecone @pinecone-database/pinecone

**Comment by pandektesoscar** [comment]
Yes this is very annoying. I have migrated to the new @langchain/pinecone so I could install the new pinecone 2.0.
But since i have a few files that still uses the langchain package and not  the @langchain/core or @langchain/openai, I am unable to install the new pinecone2.0 even though all my vectorstores is being called using the new @langchain/pinecone package...
So I guess for the time being we are still stuck on pinecone 1.3 until they can make npm relax or somthing

**Comment by digicosmos86** [comment]
Same issue here
