### ISSUE TITLE
Xata Vector Search implementation is not working

### ISSUE THREAD

**Issue by rodjosh** [langchain-ai/langchainjs#4156]
I tried everything and everytime it returned an empty array. The only way to make it work was using my own implementation:

```
import { OpenAIEmbeddings } from '@langchain/openai'
import { getXataClient } from './xata.js'

const embeddings = new OpenAIEmbeddings({
    batchSize: 1536,
})

const xata = getXataClient()

const embedding = await embeddings.embedQuery('Hello World')
const records = await xata.db.vectors.vectorSearch('embedding', embedding)

for (const record of records) {
    console.log(record.content, record.xata)
}
```

**Comment by jacoblee93** [comment]
CC @tsg would you be ok with having a look?

**Comment by tsg** [comment]
> I tried everything and everytime it returned an empty array. 

I will double check with the integration tests that it is still running, but one thing to keep in mind is that if you add a vector and then immediately search for it, it might not be indexed yet because the indexing happens async.

The integration tests do something like this to workaround: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/tests/xata.int.test.ts#L98-L101

Could it be that this is the issue?

Thanks for the ping @jacoblee93 .

**Comment by tsg** [comment]
I confirmed that the integration tests still work, for reference I ran (after unskipping):

```
OPENAI_API_KEY=sk-.... XATA_API_KEY='xau_....' XATA_DB_URL='https://....eu-west-1.xata.sh/db/langchaintest' yarn test:single './src/vectorstores/tests/xata.int.test.ts'
```

@rodjosh let me know if I can help in any way, you can also find me in the Xata discord if you need help troubleshooting.
