### ISSUE TITLE
[Feature request] Add MLC Web-LLM

### ISSUE THREAD

**Issue by pacoccino** [langchain-ai/langchainjs#4394]
Could be great to add support for MLC-AI Web-LLM

This allows to execute LLMs in the browser via WASM/WebGPU

https://github.com/mlc-ai/web-llm

**Comment by jacoblee93** [comment]
Yes this would be incredible!

**Comment by pacoccino** [comment]
I don't know much the codebase of langchain, does the suggestions of the bot are correct ?

Does this would "require significant changes to the current architecture" as the bot says, or it may be easy implementing this, as for HF's transformers.js ?

**Comment by Adrastopoulos** [comment]
@pacoccino Have you worked on this significantly? I am willing to pick this up.

**Comment by Adrastopoulos** [comment]
@pacoccino Have you made significant effort towards this? I'm willing to pick this up.

**Comment by jacoblee93** [comment]
I ended up adapting his PR on another repo here:

https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/app/lib/chat_models/webllm.ts

Still a few rough edges but if you're down to refine it we'd welcome the addition!

**Comment by Adrastopoulos** [comment]
Awesome. I'll take it on.

**Comment by stvnshpd** [comment]
Hey! I tried running latest implementation that @jacoblee93 put together, but when compiling I am getting an import error for 'Engine' from the "@mlc-ai/web-llm" library from what looks like the webllm.ts file in the langchain-community library. The webllm.ts file appears to use 'webllm.Engine()' in initialization, yet when I looked into the "@mlc-ai/web-llm" library I notice they export a 'MLCEngine' class instead of 'Engine'. Is this a known issue/discrepancy with a resolution?

**Comment by jacoblee93** [comment]
I think there was a breaking change in a recent WebLLM version a little while ago - what version did you install?

**Comment by stvnshpd** [comment]
For the "@mlc-ai/web-llm" library, I tried a sweep from 0.2.38 thru 0.2.30, and several below - including some 0.1.x releases- but didn't find any change in the error. (I did the sweep for both "@langchain/community" 0.2.0 and 0.2.1 versions)
