### ISSUE TITLE
HNSWlib similarity score calculation is incompatible with ScoreThresholdRetriever

### ISSUE THREAD

**Issue by Jtewen** [langchain-ai/langchainjs#4599]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

const cacheStore = await HNSWLib.load(path-to-vectorstore, some-embedder);

export const cacheRetriever = async () => ScoreThresholdRetriever
	.fromVectorStore(await cacheStore(), {
		minSimilarityScore: 0.9,
		kIncrement: 2,
		maxK: 100
	});

console.log((await cacheRetriever).getRelevantDocuments("hello");

### Description

HNSWLib similarity scores are inverted, where 0 is most similar and 1 is most dissimilar. This doesn't work with the ScoreThresholdRetriever as it assumes that higher scores are more similar.

### System Info

MacOS
Node v21.1.0
Langchain 0.1.24

**Comment by eduardolundgren** [comment]
I've encountered similar issue with Prisma or PGVector when retrieving relevant documents based on a query and a maximum similarity distance threshold.

The core of the problem lies in the way the original ScoreThresholdRetriever implementation compares the similarity score, which doesn't align with how databases that return vector distances operate.

Original:
```
  async getRelevantDocuments(query) {
      let currentK = 0;
      let filteredResults = [];
      do {
          currentK += this.kIncrement;
          const results = await this.vectorStore.similaritySearchWithScore(query, currentK, this.filter);
          // COMPARISON: score >= this.minSimilarityScore
          filteredResults = results.filter(([, score]) => score >= this.minSimilarityScore);
      } while (filteredResults.length >= currentK && currentK < this.maxK);
      return filteredResults.map((documents) => documents[0]).slice(0, this.maxK);
  }
```

Patched version:

```
  async getRelevantDocuments(query: string): Promise<Document[]> {
    let currentK = 0;
    let filteredResults: [Document, number][] = [];
    do {
      currentK += this.kIncrement;
      const results = await this.vectorStore.similaritySearchWithScore(query, currentK, this.filter);
      filteredResults = results.filter(([, distance]) => {
        // COMPARISON: distance <= this.maxSimilarityDistance
        return distance <= this.maxSimilarityDistance;
      });
    } while (filteredResults.length >= currentK && currentK < this.maxK);
    return filteredResults.map((documents) => documents[0]).slice(0, this.maxK);
  }
 ```

In the original implementation, a higher score indicates more relevance, whereas, in a database that returns vector distances ([see Prisma implementation](https://github.com/langchain-ai/langchainjs/blob/0c82d55e309727690208141f1538587d72eb2d86/libs/langchain-community/src/vectorstores/prisma.ts#L386)), a lower distance indicates more relevance. This inversion means that the original implementation is unsuitable for such use cases.

To address this, I've implemented a custom function to handle the filtering process appropriately. This custom function ensures that documents with a similarity distance below the threshold are filtered out correctly, considering the nature of vector distances.

I wonder if I am missing something that required this patch. If anyone else is experiencing the same problem or has any insights, please let us know.
