### ISSUE TITLE
streamEvents does not properly work on RemoteRunnable

### ISSUE THREAD

**Issue by jumski** [langchain-ai/langchainjs#5309]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Chain

```python
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai.chat_models import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

OPENAI_API_KEY = "your API key"

chain = (
    ChatPromptTemplate.from_template("Tell me a joke about {input}")
    | ChatOpenAI(model="gpt-3.5-turbo-1106", api_key=OPENAI_API_KEY)
    | StrOutputParser()
)
```

### LangServe app

```python
from fastapi import FastAPI
from langserve import add_routes
import chain

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["*"],
)

add_routes(app, chain, path='/remote-chain')

if __name__ == "__main__":
    import os
    import uvicorn

    HTTP_PORT = 8081
    uvicorn.run(app, host="0.0.0.0", port=HTTP_PORT)
```

### RemoteRunnable#streamEvents in JS

```typescript
import { RemoteRunnable } from '@langchain/core/runnables/remote';

const remoteChain = new RemoteRunnable('remote-chain');

async function streamEvents() {
  const stream = remoteChain.streamEvents({ input: "programming" }, { version: "v1" });
  
  for await (const event of stream) {
    console.log('event', event);  
  }
}
```
Expected this code to produce stream of events that one can expect from **streamEvents** and a POST request to **/stream_events**, but it hits **POST /stream** and the event stream/response looks like a regular stream response that uses SSE.

```python
import chain
import asyncio

if __name__ == "__main__":
    async def run():
        events = chain.astream_events(dict(input="programming"), version='v1')

        async for event in events:
            print(event)

    asyncio.run(run());
```

This code properly streams all the events, proving that the chain itself is streamable.

### Description

**streamEvents** called on RemoteRunnable does not seem to properly stream the events and instead posts regular **/stream** endpoint.

The chain is streamable for sure (verified in python).

I also noticed that the **chain.streamEvents** function definition that i inspect on real chain instance in the browser debug console does not look like the definition i verify in code, but instead looks like the definition for **Runnable._streamEvents**:

#### `chain.streamEvents`

![image](https://github.com/langchain-ai/langchainjs/assets/9126/baf52a3b-f46a-47c7-bc2e-b7679cbe9fc4)

#### `Runnable._streamEvents`

![image](https://github.com/langchain-ai/langchainjs/assets/9126/d24b6cd5-7839-4ad8-ad43-5dbd45435d19)

#### `RemoteRunnable.streamEvents`

![image](https://github.com/langchain-ai/langchainjs/assets/9126/24904f11-acf3-4b36-a54a-561ab8d7a66c)

#### `pnpm show langchain`

```
langchain@0.1.36 | MIT | deps: 18 | versions: 269
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.1.36.tgz
.shasum: 2f201f681d83fb265716e28e7dfcfe61fbeef2c2
.integrity: sha512-NTbnCL/jKWIeEI//Nm1oG8nhW3vkYWvEMr1MPotmTThTfeKfO87eV/OAzAyh6Ruy6GFs/qofRgQZGIe6XvXTNQ==
.unpackedSize: 4.0 MB

dependencies:
@anthropic-ai/sdk: ^0.9.1
@langchain/community: ~0.0.47
@langchain/core: ~0.1.60
@langchain/openai: ~0.0.28
@langchain/textsplitters: ~0.0.0
binary-extensions: ^2.2.0
js-tiktoken: ^1.0.7
js-yaml: ^4.1.0
jsonpointer: ^5.0.1
langchainhub: ~0.0.8
langsmith: ~0.1.7
ml-distance: ^4.0.0
openapi-types: ^12.1.3
p-retry: 4
uuid: ^9.0.0
yaml: ^2.2.1
zod-to-json-schema: ^3.22.3
zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.1.36
next: 0.2.0-rc.1

published a week ago by jacoblee93 <jacoblee93@gmail.com>
```

### pnpm: 8.14.1

**Comment by jumski** [comment]
@dosu can you confirm that RemoteRunnable should have full support for streamEvents and it should include all the events from the sub-runnables from the remote runnable?

**Comment by jumski** [comment]
@dosu in what circumstances one cannot use streamEvents or it is unfeasible to use it?

**Comment by jumski** [comment]
@dosu i am pretty sure we are onto something.

When remote chain is RunnableSequence, its sub-runnables will not be included in the streamEvents, and only events with name==RunnableSequence will be streamed.

how one can target the inner rrunnables of RunnableSequence, when the sequence chain is exposed as langserve remote runnable and consumed in JS?

**Comment by jumski** [comment]
@dosu you tripped into the vague mumbo jumbo

tell me details about implementation of streamEvents for RunnableSequence so i can understand its limitations

**Comment by jumski** [comment]
@dosu it is still not helpful.

search for code that implements streamEvents for RunnableSequence and explain to me step by step how it works

**Comment by kikohs** [comment]
I have this issue as well with an AgentExecutor, the `/stream` endpoint is called but I get all the chunks at once, like `invoke`. `steamEvents` is the same.

**Comment by mcgear** [comment]
In my case, I believe the issue boils down to a couple of things. My RemoteRunnable ends up piped in and out of some RunnableLambdas to help support input and output formatting as it is used in other chains It seems RunnableLambda does not implement its own streamEvents method, and therefore uses the implementation from Runnable. In looking at the implementation, it seems that for v1 events, the system uses streamLog:
https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/runnables/base.ts#L961C24-L961C34

And then for v2 events, it is using stream:
https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/runnables/base.ts#L898C38-L898C54

This is what seems to be causing the system to call the /stream endpoint when running with version 2. When streamEvents is called on the RunnableLambda, it is converted to a this.stream call, and causes RemoteRunnable to call the /stream endpoint?

Should the base implementation of v2 event streaming be calling `outerThis.streamEvents` instead of just .stream? 

I believe this issue would occur with a RemoteRunnable that is piped with any of the core runnable types that rely on the base streamEvents implementation... Like RunnableSequence, RunnableMap, RunnableAssign and so on.

@dosu thoughts?

**Comment by mcgear** [comment]
Well, in hindsight, it makes sense, outerThis.streamEvents seems to put everything in an endless loop, so that probably isn't the solution. I don't know enough about the inner workings of langchainjs to really knokw what the right solution is here.

The issue only arises with RemoteRunnable in the chain.

@dosu Do you have thoughts on how to fix the issue with a lot of the core Runnables switching to stream on streamEvents and causing RemoteRunnable to call the wrong endpoint?
