### ISSUE TITLE
Custom azureOpenAIApiBasePath should be applied also with azureADTokenProvider

### ISSUE THREAD

**Issue by aleclair-KoAi** [langchain-ai/langchainjs#5520]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```js
const model = new AzureChatOpenAI({
    azureADTokenProvider: azureADTokenProvider,
    azureOpenAIApiInstanceName: "myapp-api",
    azureOpenAIApiCompletionsDeploymentName: "mydeployment",
    azureOpenAIBasePath:
      "https://myapp-api.mydomain.com/openai/deployments",
    azureOpenAIApiDeploymentName: "maia-gpt-35-turbo-1106",
    azureOpenAIApiVersion: "2024-02-15-preview",
  });
```

### Error Message and Stack Trace (if applicable)

Wrong url called, it will be https://myapp-api.openai.azure.com/openai/deployments/mydeployment/chat/completions instead of https://myapp-api.mydomain.com/openai/deployments/mydeployment/chat/completions
I also noted that I should use AZURE_OPENAI_API_DEPLOYMENT_NAME and AZURE_OPENAI_API_VERSION to get azureOpenAIApiDeploymentName and azureOpenAIApiVersion works

### Description

* I am trying to use langchain 0.2.1 to use Azure APIM to have Azure OpenAI with Oauth.
* I have a custom url for this endpoint by langchain force to have an url ending by openai.azure.com with azureADTokenProvider
* I want to use azureOpenAIBasePath and azureOpenAIApiDeploymentName to have `${azureOpenAIBasePath}/${azureOpenAIApiDeploymentName}` url in getEndpoint function

### System Info

langchain version: '0.2.1'
platform mac
node 18

**Comment by aleclair-KoAi** [comment]
@dosu to my mind, in order to prioritize azureOpenAIBasePath it should be 
```js
if (
    (azureOpenAIApiKey || azureADTokenProvider) &&
    azureOpenAIBasePath &&
    azureOpenAIApiDeploymentName
  ) {
    return `${azureOpenAIBasePath}/${azureOpenAIApiDeploymentName}`;
  }
  ```

**Comment by jeasonnow** [comment]
https://github.com/langchain-ai/langchainjs/blob/96324b5a2f473dde7853522884369805b9aa848a/libs/langchain-openai/src/azure/chat_models.ts#L39-L46

https://github.com/langchain-ai/langchainjs/blob/96324b5a2f473dde7853522884369805b9aa848a/libs/langchain-openai/src/chat_models.ts#L412-L434

This approach will result in the direct settings of `azureOpenAIApiDeploymentName`, `azureOpenAIApiKey`, and `azureOpenAIApiVersion` becoming `undefined`. Moreover, because `getEndpoint` will determine whether to correctly concatenate based on the `chatModel` properties:  `azureOpenAIApiKey`, `azureOpenAIBasePath`, and `azureOpenAIApiDeploymentName`, it will lead to this issue.

https://github.com/langchain-ai/langchainjs/blob/96324b5a2f473dde7853522884369805b9aa848a/libs/langchain-openai/src/utils/azure.ts#L42-L48

**Comment by jeasonnow** [comment]
> @dosubot to my mind, in order to prioritize azureOpenAIBasePath it should be
> 
> ```js
> if (
>     (azureOpenAIApiKey || azureADTokenProvider) &&
>     azureOpenAIBasePath &&
>     azureOpenAIApiDeploymentName
>   ) {
>     return `${azureOpenAIBasePath}/${azureOpenAIApiDeploymentName}`;
>   }
> ```
Oh, I forgot about that...

**Comment by aleclair-KoAi** [comment]
Thanks a lot for your quick reply, I understand now and yes if azureOpenAIBasePath could be solved too, it will be perfect

**Comment by Jellyman447** [comment]
Approved
