### ISSUE TITLE
GoogleGenerativeAIError: [400 Bad Request] Invalid JSON payload received.

### ISSUE THREAD

**Issue by rossanodr** [langchain-ai/langchainjs#5825]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code 
`import { BaseMessage } from "@langchain/core/messages";
import {
  ChatPromptTemplate,
  MessagesPlaceholder,
} from "@langchain/core/prompts";
import { RunnableConfig } from "@langchain/core/runnables";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { END, START, StateGraph } from "@langchain/langgraph";
import { githubTool, invoiceTool, weatherTool } from "./tools";

interface AgentExecutorState {
  input: string;
  chat_history: BaseMessage[];
  /**
   * The plain text result of the LLM if
   * no tool was used.
   */
  result?: string;
  /**
   * The parsed tool result that was called.
   */
  toolCall?: {
    name: string;
    parameters: Record<string, any>;
  };
  /**
   * The result of a tool.
   */
  toolResult?: Record<string, any>;
}

const invokeModel = async (
  state: AgentExecutorState,
  config?: RunnableConfig
): Promise<Partial<AgentExecutorState>> => {
  const initialPrompt = ChatPromptTemplate.fromMessages([
    [
      "system",
      `You are a helpful assistant. You're provided a list of tools, and an input from the user.\n
Your job is to determine whether or not you have a tool which can handle the users input, or respond with plain text.`,
    ],
    new MessagesPlaceholder({
      variableName: "chat_history",
      optional: true,
    }),
    ["human", "{input}"],
  ]);

  const tools = [githubTool, invoiceTool, weatherTool];

  const llm = new ChatGoogleGenerativeAI({
    apiKey: process.env.GOOGLE_API_KEY,
    model: "gemini-1.5-flash",
    streaming: true,
    maxConcurrency: 2,
    temperature: 0,
    apiVersion: "v1beta",
  }).bindTools(tools);
  const chain = initialPrompt.pipe(llm);
  const result = await chain.invoke(
    {
      input: state.input,
      chat_history: state.chat_history,
    },
    config
  );

  if (result.tool_calls && result.tool_calls.length > 0) {
    return {
      toolCall: {
        name: result.tool_calls[0].name,
        parameters: result.tool_calls[0].args,
      },
    };
  }
  return {
    result: result.content as string,
  };
};

const invokeToolsOrReturn = (state: AgentExecutorState) => {
  if (state.toolCall) {
    return "invokeTools";
  }
  if (state.result) {
    return END;
  }
  throw new Error("No tool call or result found.");
};

const invokeTools = async (
  state: AgentExecutorState,
  config?: RunnableConfig
): Promise<Partial<AgentExecutorState>> => {
  if (!state.toolCall) {
    throw new Error("No tool call found.");
  }
  const toolMap = {
    [githubTool.name]: githubTool,
    [invoiceTool.name]: invoiceTool,
    [weatherTool.name]: weatherTool,
  };

  const selectedTool = toolMap[state.toolCall.name];
  if (!selectedTool) {
    throw new Error("No tool found in tool map.");
  }
  const toolResult = await selectedTool.invoke(
    state.toolCall.parameters,
    config
  );
  return {
    toolResult: JSON.parse(toolResult),
  };
};

export function agentExecutor() {
  const workflow = new StateGraph<AgentExecutorState>({
    channels: {
      input: null,
      chat_history: null,
      result: null,
      toolCall: null,
      toolResult: null,
    },
  })
    .addNode("invokeModel", invokeModel)
    .addNode("invokeTools", invokeTools)
    .addConditionalEdges("invokeModel", invokeToolsOrReturn)
    .addEdge(START, "invokeModel")
    .addEdge("invokeTools", END);

  const graph = workflow.compile();
  return graph;
}
`
Is exacly the same as the repo https://github.com/bracesproul/gen-ui
But I'm trying to use ChatGoogleGenerativeAI.

### Error Message and Stack Trace (if applicable)

This runs the error
⨯ unhandledRejection: GoogleGenerativeAIError: [400 Bad Request] Invalid JSON payload received. Unknown name "default" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[0].value': Cannot find field.
Invalid JSON payload received. Unknown name "exclusiveMinimum" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[2].value': Cannot find field.
Invalid JSON payload received. Unknown name "exclusiveMinimum" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[3].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools[0].function_declarations[2].parameters.properties[2].value': Cannot find field. [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"tools[0].function_declarations[1].parameters.properties[1].value.items.properties[0].value","description":"Invalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[0].value': Cannot find field."},{"field":"tools[0].function_declarations[1].parameters.properties[1].value.items.properties[2].value","description":"Invalid JSON payload received. Unknown name \"exclusiveMinimum\" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[2].value': Cannot find field."},{"field":"tools[0].function_declarations[1].parameters.properties[1].value.items.properties[3].value","description":"Invalid JSON payload received. Unknown name \"exclusiveMinimum\" at 'tools[0].function_declarations[1].parameters.properties[1].value.items.properties[3].value': Cannot find field."},{"field":"tools[0].function_declarations[2].parameters.properties[2].value","description":"Invalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[2].parameters.properties[2].value': Cannot find field."}]}]

### Description

I'm just trying to use Gemini instead of OpenAI

### System Info

   "@langchain/community": "^0.2.10",
    "@langchain/core": "^0.2.6",
    "@langchain/google-genai": "^0.0.20",
    "@langchain/langgraph": "^0.0.23",

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by phuhh98** [comment]
I'm trying to use ChatGoogleGenerativeAI.withStructuredOutput(zodSchema) to convert result to my desire json structure as in the example on Langchain JS [here](https://js.langchain.com/v0.2/docs/integrations/chat/google_generativeai#withstructuredoutput) via function calling approach and facing the same issue.

My observation is that .withStructuredOutput(zodSchema) method consume the zodSchema and use [zod](https://www.npmjs.com/package/zod) + [zod-to-json-schema](https://www.npmjs.com/package/zod-to-json-schema) package internally to convert to json and use it to describe parameters in function declarations.

The problem is that the internal [utils](https://github.com/langchain-ai/langchainjs/blob/7ef4fdb162053bdef58671cb96a6ed0ed5164172/libs/langchain-google-genai/src/utils/zod_to_genai_parameters.ts) that they are using only stripping off own properties.
Function declarations should follow this [interface](https://github.com/google-gemini/generative-ai-js/blob/5f9e393313f3d0de1376883d981f377600d67fa6/packages/main/types/function-calling.ts#L68) from @google/gen-ai and the json schema should have "type" key with all upper case letters as in this [enum](https://github.com/google-gemini/generative-ai-js/blob/5f9e393313f3d0de1376883d981f377600d67fa6/packages/main/types/function-calling.ts#L87)
which is also described in the google genai doc for [example function declaration](https://ai.google.dev/gemini-api/docs/function-calling/tutorial?lang=node#create-function-declarations).

It could be case-sensitive condition for this particular value for "type" key on the server.

I've tried to create literal function declaration objects which used this [enum](https://github.com/google-gemini/generative-ai-js/blob/5f9e393313f3d0de1376883d981f377600d67fa6/packages/main/types/function-calling.ts#L87) and bound it to the model and its works.

Addition to this, there's another issue to parse json output function call in the response from gemini. Gemini return function calls info to invoke in **message.kwargs.tool_calls**, which is different from what is supported by **[JsonOutputToolsParser](https://github.com/langchain-ai/langchainjs/blob/7ef4fdb162053bdef58671cb96a6ed0ed5164172/langchain/src/output_parsers/openai_tools.ts#L27)** with method [parseResult](https://github.com/langchain-ai/langchainjs/blob/7ef4fdb162053bdef58671cb96a6ed0ed5164172/langchain/src/output_parsers/openai_tools.ts#L51), it try to find function call args in **message.additional_kwargs.tool_calls** which is not where these argument being return when using gemini.

With your case, you could check wheter the tools in **import { githubTool, invoiceTool, weatherTool } from "./tools";** that you are using is declare to not using zodSchema - just for this case - and follow [StructuredToolInterface](https://github.com/langchain-ai/langchainjs/blob/7ef4fdb162053bdef58671cb96a6ed0ed5164172/langchain-core/src/tools.ts#L37) or [FunctionDeclaration](FunctionDeclaration ) and the example from google ai I have mentioned earlier.

Hope the team could to something with the zodSchema transformer that they use and for an adapter to parse arguments in response a map it to OpenAI so that langchain could handle it later with pipe without further change in core module.

**Comment by phuhh98** [comment]
refer to this [issue](https://github.com/google-gemini/generative-ai-js/issues/153)

**Comment by vixalien** [comment]
this is still not fixed
