### ISSUE TITLE
PostgresChatMessageHistory: error: column "message" does not exist

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [langchain-ai/langchainjs#5891]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

# Example Code:

```typescript
import pg, { PoolConfig } from "pg";

import { PostgresChatMessageHistory } from "@langchain/community/stores/message/postgres";
import { ChatOpenAI } from "@langchain/openai";
import { RunnableWithMessageHistory } from "@langchain/core/runnables";
import {
  ChatPromptTemplate,
  MessagesPlaceholder,
} from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";

const poolConfig: PoolConfig = {
  host: 'localhost',
  port: 5432,
  user: '....',
  password: '....',
  database: '.....',
}

const pool = new pg.Pool(poolConfig)

const apiKey = '...';

const model = new ChatOpenAI({ apiKey: apiKey, model: 'gpt-3.5-turbo', temperature: 0, n: 3 })

const prompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    "You are a helpful assistant. Answer all questions to the best of your ability.",
  ],
  new MessagesPlaceholder("chat_history"),
  ["human", "{input}"],
]);

const chain = prompt.pipe(model).pipe(new StringOutputParser());

const chainWithHistory = new RunnableWithMessageHistory({
  runnable: chain,
  inputMessagesKey: "input",
  historyMessagesKey: "chat_history",
  getMessageHistory: async (sessionId) => {
    const chatHistory = new PostgresChatMessageHistory({
      tableName: 'directories',
      sessionId,
      pool,
    });
    return chatHistory;
  },
});

const res1 = await chainWithHistory.invoke(
  {
    input: "Hi! I'm Chris.",
  },
  { configurable: { sessionId: "langchain-test-session" } }
);
console.log(res1);


const res2 = await chainWithHistory.invoke(
  { input: "Provide me with adventure recommendations in the municipality of San Juan." },
  { configurable: { sessionId: "langchain-test-session" } }
);
console.log(res2);

await pool.end();
```

### Error Message and Stack Trace (if applicable)

# Error

```shell
chrismperez@Chriss-MBP vt-ai % yarn start
yarn run v1.22.10
$ esno src/index.ts
/Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/pg-pool/index.js:45
    Error.captureStackTrace(err)
          ^

error: column "message" does not exist
    at /Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresChatMessageHistory.getMessages (file:///Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/@langchain/community/dist/stores/message/postgres.js:115:21)
    at async RunnableWithMessageHistory._enterHistory (file:///Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/@langchain/core/dist/runnables/history.js:212:26)
    at async file:///Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/@langchain/core/dist/runnables/base.js:1484:34 {
  length: 106,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3513',
  routine: 'errorMissingColumn'
}

Node.js v18.18.0
error Command failed with exit code 1.
```

### Description

# Description:

The error is occurring when I try to specify the table I want to use in the **tableName** property of the **PostgresChatMessageHistory** class. When executing the langchain code the **langchain_chat_histories** table does not exist.

But if I don't use the **tableName** property the code responds correctly.
<img width="741" alt="1" src="https://github.com/langchain-ai/langchainjs/assets/21962584/8e39af29-7d2a-4bc4-a960-7805d2ebd96c">

### System Info

# System Info:

- [x] plataform: `Mac M1`
- [x] node: `v18.18.0`
- [x] yarn: `v1.22.10`
- [x] package.json
```json
  "dependencies": {
    "@langchain/community": "^0.2.13",
    "@langchain/openai": "^0.0.33",
    "@types/pg": "^8.11.6",
    "pg": "^8.12.0",
    "typeorm": "^0.3.20"
  },
```

**Comment by ChrisMichaelPerezSantiago** [comment]
@dosue 

The **langchain_chat_histories** table initially does not exist.

**langchain_chat_histories** is the table that should contain:
```sql
id SERIAL PRIMARY KEY,
session_id VARCHAR(255) NOT NULL,
message JSONB NOT NULL
```

**Comment by ChrisMichaelPerezSantiago** [comment]
@dosue
Your solution is not correct.I want to consume the data (ask questions) from the **directories** table.

**Comment by ChrisMichaelPerezSantiago** [comment]
@dosue

Your solution is not correct.

The **tableName** property is used to specify the table that I want to use to consume data. But the **langchain_chat_histories** table must be created to keep record of the conversation history.


The error I am having is the following:
```shell
/Users/chrismperez/Desktop/chris-projects/vt-ai/node_modules/pg-pool/index.js:45
 Error.captureStackTrace(err)
 ^
error: column "message" does not exist
```

**Comment by ChrisMichaelPerezSantiago** [comment]
@dosue

The directory table contains these columns: **id, title, description, phone, created_at, updated_at, published_at, created_by_id, updated_by_id**

**Comment by MJDeligan** [comment]
If a table with the name `directories` already exists, then the message history will not create a new table. The `tableName` you pass to the message history is the table you want the history to use to store messages. This defaults to `langchain_chat_histories`. It looks like you've created a `directories` table for some other purpose and are now passing that name to the message history. The history will assume that the existing table whose name you've passed is a table that follows the chat message table schema, which it does not since 
> The directory table contains these columns: id, title, description, phone, created_at, updated_at, published_at, created_by_id, updated_by_id

I'm not sure why you are passing the name of that table to the message history. If you need that table, then you should use another table name. If you don't need it, then drop it and use the `directories` name.

**Comment by ChrisMichaelPerezSantiago** [comment]
@MJDeligan Thanks for the clarification.

And how can I interact with the data of a particular table?

**Comment by MJDeligan** [comment]
I'm guessing you cannot query the data based on the input. Retrieval will depend on whether the data can be reliably searched by exact or pattern matching. If for example you have a table with people and those people are associated with a unique username and you want to answer queries such as "How old is lisab561?" then tool calling would be the right idea, since the llm can infer the username and issue a tool call, which you would implement as a function that performs the sql query. 

If however you want to retrieve data which can't be matched exactly or by some pattern and instead requires a semantic match then you need a vectorstore with embeddings for the data you want to match.

A case for this would be if your people data has descriptions for people and you want to handle queries such as "What's the name of a kind and loving person". User lisab561 might have a description like "Does sports and especially loves climbing. She's a lovely and nice person.". Obviously this is not an exact match but semantically her description fits the query and a vectorstore would be able to match the query to the data.
