### ISSUE TITLE
Can't use ChatGoogleGenerativeAI with tools in Langraph

### ISSUE THREAD

**Issue by cnarte** [langchain-ai/langchainjs#6833]
I'm trying to use google generative-ai package with langraph but getting a unhandled response for llm call inside the package with tool call.

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code File < node_modules\@langchain\google-genai\dist\chat_models.js >  ::
```        const generationResult = (0, common_js_1.mapGenerateContentResultToChatResult)(res.response, {
            usageMetadata,
        });
            await runManager?.handleLLMNewToken(generationResult.generations[0].text ?? "");
            return generationResult;
    }


### Error Message and Stack Trace (if applicable)

``` node_modules\@langchain\google-genai\dist\chat_models.cjs:276
        await runManager?.handleLLMNewToken(generationResult.generations[0].text ?? "");
                                                                            ^     

TypeError: Cannot read properties of undefined (reading 'text')

### Description

I'm trying to use ChatGoogleGenerativeAI for langraph. also defined the tools in gemeni tool format. But the tool call agents are not working.

### System Info

```  "dependencies": {
        "@google-cloud/aiplatform": "^3.29.0",
        "@google-cloud/vertexai": "^1.7.0",
        "@langchain/anthropic": "^0.3.0",
        "@langchain/community": "^0.2.25",
        "@langchain/google-genai": "^0.0.25",
        "@langchain/google-vertexai": "^0.0.27",
        "@langchain/google-vertexai-web": "^0.0.27",
        "@langchain/groq": "^0.0.17",
        "@langchain/langgraph": "^0.0.34",
        "@langchain/ollama": "^0.0.4",
        "@langchain/openai": "^0.2.11",
        "@types/node": "^22.5.4",
        "axios": "^1.7.3",
        "dotenv": "^16.4.5",
        "langchain": "^0.2.13",
        "mongoose": "^8.5.2",
        "node-fetch": "^3.3.2",
        "readline-sync": "^1.4.10",
        "tslab": "^1.0.22",
        "typescript": "^5.5.4",
        "wwebjs-mongo": "^1.1.0"
      }

**Comment by cnarte** [comment]
But how can I edit the Package implementation?

**Comment by cnarte** [comment]
@dosu that wont solve problem just throw a new error.

**Comment by afirstenberg** [comment]
I'd need to dig into the `@langchain/google-genai` package to be sure, but my guess is that this isn't caused by tools specifically but that a `finishReason` of "SAFETY" or something else is being triggered. In these cases, there is no text returned, so trying to access the `text` element (which is what is done internally) is triggering the exception.

A slightly biased suggestion, but you may wish to switch to using the `@langchain/google-gauth` or `@langchain/google-webauth` packages instead. These don't _avoid_ the issue, but they do let you manage it a bit better with a `SecurityManager`. You'll then be using the `ChatGoogle` class.

Make sure you are using version 0.1.0 of either and version 0.1.1 of `@langchain/google-common`. You'll also need to explicitly depend on `@langchain/common` version 0.3.0.
